crystaltriangle/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("website.urls", namespace="website")),
]

website/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact")
]

website/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

now = timezone.now()

class Blog(models.Model):
    date_added = models.DateField(default=now)
    title = models.CharField(max_length=150)
    intro = models.CharField(max_length=200)
    fullText = models.TextField()
    image = models.FileField(max_length=150, upload_to="blogs/images", blank=True, null=True)

    def __str__(self):
        return self.title

class SliderImages(models.Model):
    date_added = models.DateField(default=now)
    text = models.TextField()
    image = models.FileField(max_length=150, upload_to="slideshow-images")

    def __str__(self):
        return self.text

website/views.py
from django.shortcuts import render
from .models import SliderImages, Blog


def index(request):
    slides = SliderImages.objects.all().order_by("-date_added")[:3]
    blogs = Blog.objects.all().order_by("-date_added")[:2]

    return render(request, "index.html", {
    "slides":slides, "blogs":blogs,
    })


def contact(request):

    return render(request, "contact.html", {
    
    })

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock title %} - CrystalTriangle</title>
<meta name="author" content="Delhi Nerds">
<meta name="description" content="{{description}}">
<meta name="keywords" content="{{keywords}}">

<!-- SOCIAL MEDIA META -->
<meta property="og:description" content="{{description}}">
<meta property="og:image" content="../../www.themezinho.net/o/preview.html">
<meta property="og:site_name" content="Crystal Triangle">
<meta property="og:title" content="Crystal Triangle">
<meta property="og:type" content="website">
<meta property="og:url" content="http://www.crystaltriangle.com">

<!-- FAVICON FILES -->
<link href="{% static "ico/apple-touch-icon-144-precomposed.png" %}" rel="apple-touch-icon-precomposed" sizes="144x144">
<link href="{% static "ico/apple-touch-icon-114-precomposed.png" %}" rel="apple-touch-icon-precomposed" sizes="114x114">
<link href="{% static "ico/apple-touch-icon-72-precomposed.png" %}" rel="apple-touch-icon-precomposed" sizes="72x72">
<link href="{% static "ico/apple-touch-icon-57-precomposed.png" %}" rel="apple-touch-icon-precomposed">
<link href="{% static "ico/favicon.png" %}" rel="shortcut icon">

<!-- CSS FILES -->
<link href="{% static "css/main.css" %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="overflow-hidden">
  {% include "menu.html" %}
  <main>
    <!-- end transition-overlay -->
    <header class="header">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header"> <a class="navbar-brand transition" href="{% url "website:index" %}"> <img src="{% static "images/logo.png" %}" alt="Image"></a>
            <div class="sandwich-menu"> <span></span> <span></span> <span></span> <span></span> </div>
          </div>
          <!-- end navbar-header -->
        </div>
        <!-- end container-fluid -->
      </nav>
    </header>
    <!-- end header -->

{% block content %}
{% endblock content %}

<section class="hire-us wow fadeIn">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3>Would you like to hire us?</h3>
      </div>
      <!-- end col-12 -->
    </div>
    <!-- end row -->
  </div>
  <!-- end container -->
</section>
<!-- end hire-us -->


<footer class="footer">
  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-6"> <span class="copyright">© 2017 Crystal Triangle. All Rights Reserved</span> </div>
    <!-- end col-4 -->
    <div class="col-md-4 col-sm-4 col-xs-6">
      <ul class="social-media">
        <li><a href="#"><i class="ion-social-facebook"></i></a></li>
        <li><a href="#"><i class="ion-social-twitter"></i></a></li>
        <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
        <li><a href="#"><i class="ion-social-youtube"></i></a></li>
        <li><a href="#"><i class="ion-social-vimeo"></i></a></li>
      </ul>
    </div>
    <!-- end col-4 -->
    <div class="col-md-4 col-sm-4 hidden-xs"> <span class="creation">Designed by Delhi Nerds with<i class="ion-heart"></i> in Nuevo Delhi.</span> </div>
    <!-- end col-4 -->
  </div>
  <!-- end row -->
</footer>
<!-- end footer -->
</main>

<!-- JS FILES -->
<script src="{% static "js/jquery.min.js" %}"></script>
<script type="text/javascript">
(function($) {
$(window).load(function(){
  $("body").removeClass("overflow-hidden");
  $(".preloader").addClass("move-up");
  $(".header").addClass("move-down");
  $(".site-hero").addClass("move-up");
});
})(jQuery)
</script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/masonry.js" %}"></script>
<script src="{% static "js/wow.js" %}"></script>
<script src="{% static "js/jquery.stellar.js" %}"></script>
<script src="{% static "js/jquery.vopacity.js" %}"></script>
<script src="{% static "js/jquery.fancybox.js" %}"></script>
<script src="{% static "js/slick.min.js" %}"></script>
<script src="{% static "js/jquery.themepunch.tools.min.js" %}" type="text/javascript" ></script>
<script src="{% static "js/jquery.themepunch.revolution.min.js" %}" type="text/javascript"></script>
<script type="text/javascript">
var tpj=jQuery;
        var revapi4;
        tpj(document).ready(function() {
          if(tpj("#rev_slider_4_1").revolution == undefined){
            revslider_showDoubleJqueryError("#rev_slider_4_1");
          }else{
            revapi4 = tpj("#rev_slider_4_1").show().revolution({
              sliderType:"standard",
              jsFileLocation:"js/",
              sliderLayout:"fullscreen",
              dottedOverlay:"none",
              delay:9000,
              navigation: {
                keyboardNavigation:"off",
                keyboard_direction: "horizontal",
                mouseScrollNavigation:"off",
                onHoverStop:"off",
                touch:{
                  touchenabled:"on",
                  swipe_threshold: 75,
                  swipe_min_touches: 1,
                  swipe_direction: "horizontal",
                  drag_block_vertical: false
                }
                ,
                              bullets: {
                                  enable: true,
                                  hide_onmobile: false,
                                  style: "uranus",
                                  hide_onleave: false,
                                  direction: "horizontal",
                                  h_align: "center",
                                  v_align: "bottom",
                                  h_offset: 20,
                                  v_offset: 40,
                                  space: 5,
                                  tmp: '<span class="tp-bullet-inner"></span>'
                              }
                          },
              viewPort: {
                enable:true,
                outof:"pause",
                visible_area:"80%"
              },
              responsiveLevels:[1240,1024,778,480],
              gridwidth:[1240,1024,778,480],
              gridheight:[600,600,500,400],
              lazyType:"none",
              shadow:0,
              spinner:"off",
              stopLoop:"off",
              stopAfterLoops:-1,
              stopAtSlide:-1,
              shuffle:"off",
              autoHeight:"off",
              fullScreenAlignForce:"on",
              fullScreenOffsetContainer: "0",
              fullScreenOffset: "0",
              disableProgressBar:"on",
              hideThumbsOnMobile:"off",
              hideSliderAtLimit:0,
              hideCaptionAtLimit:0,
              hideAllCaptionAtLilmit:0,
              debugMode:false,
              fallbacks: {
                simplifyAll:"off",
                nextSlideOnWindowFocus:"off",
                disableFocusListener:false,
              }
            });
          }
        });	/*ready*/
</script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.actions.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.carousel.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.kenburn.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.layeranimation.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.migration.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.navigation.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.parallax.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.slideanims.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/extensions/revolution.extension.video.min.js" %}"></script>
<script src="{% static "js/scripts.js" %}"></script>
</body>

</html>

templates/blogo-detail.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from themezinho.net/o/blogo-detail.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 08 Feb 2016 08:55:43 GMT -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>O Digital - Creative Portfolio</title>
<meta name="author" content="Themezinho">
<meta name="description" content="Cretive Portfoli Html Template">
<meta name="keywords" content="creative, case, study, portfolio, thumbs, gallery, blog, work, project">

<!-- SOCIAL MEDIA META -->
<meta property="og:description" content="O Digital - Creative Portfolio">
<meta property="og:image" content="../../www.themezinho.net/o/preview.html">
<meta property="og:site_name" content="O">
<meta property="og:title" content="O">
<meta property="og:type" content="website">
<meta property="og:url" content="http://www.themezinho.net/o-digital">

<!-- TWITTER META -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@O">
<meta name="twitter:creator" content="@O">
<meta name="twitter:title" content="O">
<meta name="twitter:description" content="O Digital - Creative Portfolio">
<meta name="twitter:image" content="../../www.themezinho.net/o/preview.html">

<!-- FAVICON FILES -->
<link href="ico/apple-touch-icon-144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144">
<link href="ico/apple-touch-icon-114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114">
<link href="ico/apple-touch-icon-72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72">
<link href="ico/apple-touch-icon-57-precomposed.png" rel="apple-touch-icon-precomposed">
<link href="ico/favicon.png" rel="shortcut icon">

<!-- CSS FILES -->
<link href="css/main.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="top-menu">
  <ul>
    <li><a href="abouto.html" class="transition"><span data-hover="ABOUTO">ABOUTO</span></a></li>
    <li><a href="worko.html" class="transition"><span data-hover="WORKO">WORKO</span></a></li>
    <li><a href="blogo.html" class="transition"><span data-hover="BLOGO">BLOGO</span></a></li>
    <li><a href="contacto.html" class="transition"><span data-hover="CONTACTO">CONTACTO</span></a></li>
  </ul>
</nav>
<!-- end top-menu -->
<main>
  <div class="preloader">
    <div class="table">
      <div class="inner">
        <figure><img src="images/preloader.gif" alt="Image"></figure>
      </div>
      <!-- end inner --> 
    </div>
    <!-- end table --> 
  </div>
  <!-- end preloader -->
  <div class="transition-overlay">
    <div class="inner"></div>
    <!-- end inner --> 
  </div>
  <!-- end transition-overlay -->
  <header class="header">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header"> <a class="navbar-brand transition" href="index.html"> <img src="images/logo.png" alt="Image"></a>
          <div class="sandwich-menu"> <span></span> <span></span> <span></span> <span></span> </div>
        </div>
        <!-- end navbar-header --> 
      </div>
      <!-- end container-fluid --> 
    </nav>
  </header>
  <!-- end header -->
  <section class="site-hero">
    <div class="hero-inner hero-bg3">
      <div class="table text-center">
        <div class="inner">
          <h2>BLOG</h2>
          <h5>We kraft expreriences</h5>
        </div>
      </div>
    </div>
    <!-- end pages-hero --> 
  </section>
  <!-- end site-hero -->
  <section class="blog">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="blog-post wow fadeIn" data-wow-delay="0.1s">
            <figure class="post-image"><img src="images/blog-image1.jpg" alt="Image"></figure>
            <h3 class="post-title"><a href="#">A Guide To Simple And Painless Mobile User Testing</a></h3>
            <p class="post-desc">The incredible growth of mobile and the proliferation of mobile devices has made the UX designer’s job more challenging and interesting. It also means that <b> user-testing mobile apps and websites is an essential</b> component of the UX toolkit.</p>
          <p>A new year provides a natural chance to take a look back and reflect on some of the more amazing things that happened. Here at STORY, we’re constantly changing so rare is the moment when we take a second to celebrate the successes – from collaborations to super cool events. Since we have a bit of a breather as we prepare for our next STORY (opening later this January) we thought we’d take a second to reminisce on the past year.</p>
          <p>To ring in 2015, we teamed up with the editors at Yahoo to explore how to be your very best – from how to be beautiful with Bobbi Brown and chic with Joe Zee to be a little more healthy with Michele Promaulayko. Highlights: Getting to break it down with Joe Zee and discovering the cosmic goodness of Moon Juice thanks to our friend, Yahoo Food editor Kerry Diamond.</p>
          <p>What’s your STORY? That’s the question we set out to explore (and inspire you to answer) in partnership with Awesomeness TV, the largest network for teen creators on YouTube. To bring the “me” manifesto to life we invited a handful of Awesomeness’ personalities: Ingrid Nielson, Sawyer Hartman, Connor Franta, and more to help us curate items that expressed their POV. Highlights: An in-store PHHHOTO booth, an IRL conversation with Ingrid Nielson, and our dreamy collaboration with artist Samantha Hahn.</p>
          <blockquote>Spring had us thinking about squad goals when we teamed up</blockquote>
          <p>What happens when an idea intersects with the resources to bring it to life? In our case the result was Creativity, a concept that turned our store into a design sanctuary, highlighted by inventions from the Lexus Design Award – an international design competition held annually in Milan. Highlights: An interactive light installation by Sachem Arvidson, the U.S. debut of 2014 LDA Winner Sebastian Scherer’s Iris lamp, and a Pitch Night with Bezar founder Bradford Shellhammer and Surface Magazine Editor-in-Chief Spencer Bailey.</p>
          <p>Follow your art. In August it lead us to Instagram sensation and multi-hyphenate artist Donald Robertson, who we enlisted to takeover our space by art bombing the walls and lending his artistic vision to an array of collaborative products. Highlights (almost too many to count): The release of Robertson’s fashion-forward children’s book, “Mitford at the Fashion Zoo,” a DIY station produced in collaboration with Bow + Drape, and arted-on UrbanEars headphones, Mi Cielo tees, Diet Coke bottles, Canada Goose jackets and more.</p>
          <p>At STORY we talk a lot about experience per square foot and the idea. Fact is: today you can have just about anything delivered to your door in an instant, so there’s a greater value placed on what you get beyond the item itself. In the world of retail this has taken shape through the growth of brick and mortar locations where you can get a hot towel shave with your Harry’s razor. In 2016, we see this trend giving way to an economy that transacts by way of experience: from The School of Life’s drop-in workshops to pop-up museums devoted to feelings.</p>
          <p>The ‘slow’ movement has been gaining steam for some time, particularly as it applies to food and even fashion. But as digital technologies become more omnipresent in our every day lives (see NYC’s high speed Internet phone booths), there becomes a greater nostalgia and appreciation for the days when you didn’t have everything in the palm of your hand. In 2016 we see this supporting efforts to disconnect from technology, whether at a mediation studio or Pause an app that puts relaxation at your fingertips, while also conditioning an increased connection to hand-crafted goods, foods – even face to face communication.</p>
          </div>
          <!-- end blog-post -->
        </div>
        <!-- end col-12 -->
      </div>
      <!-- end row --> 
    </div>
    <!-- end container --> 
  </section>
  <!-- end blog -->
  <footer class="footer">
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-6"> <span class="copyright">© 2015 O Digital. All Rights Reserved</span> </div>
      <!-- end col-4 -->
      <div class="col-md-4 col-sm-4 col-xs-6">
        <ul class="social-media">
          <li><a href="#"><i class="ion-social-facebook"></i></a></li>
          <li><a href="#"><i class="ion-social-twitter"></i></a></li>
          <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
          <li><a href="#"><i class="ion-social-youtube"></i></a></li>
          <li><a href="#"><i class="ion-social-vimeo"></i></a></li>
        </ul>
      </div>
      <!-- end col-4 -->
      <div class="col-md-4 col-sm-4 hidden-xs"> <span class="creation">By Themezinho with <i class="ion-heart"></i> in Istanbul</span> </div>
      <!-- end col-4 --> 
    </div>
    <!-- end row --> 
  </footer>
  <!-- end footer --> 
</main>

<!-- JS FILES --> 
<script src="../../ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
<script type="text/javascript">
(function($) {
	$(window).load(function(){
		$(".preloader").addClass("move-up");
		$(".header").addClass("move-down");
		$(".site-hero").addClass("move-up");
	});
})(jQuery)
</script> 
<script src="js/bootstrap.min.js"></script> 
<script src="js/masonry.js"></script> 
<script src="js/wow.js"></script> 
<script src="js/jquery.stellar.js"></script> 
<script src="js/jquery.vopacity.js"></script> 
<script src="js/jquery.fancybox.js"></script>  
<script src="js/slick.min.js"></script> 
<script src="js/scripts.js"></script>
</body>

<!-- Mirrored from themezinho.net/o/blogo-detail.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 08 Feb 2016 08:55:43 GMT -->
</html>

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
Contact Us
{% endblock title %}

{% block content %}

  <section class="site-hero">
    <div id="map"> </div>
  </section>
  <!-- end pages-hero -->
  <section class="contact-us">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-12 wow fadeIn" data-wow-delay="0.1s">
          <h4>ADDRESS</h4>
          <address>
          55 East 52nd Street 21st Floor<br>
          New York, NY 10022 USA
          </address>
        </div>
        <!-- end col-4 -->
        <div class="col-md-4 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.1s">
          <h4>PHONES</h4>
          <p>t: 1 (212) 446 7000<br>
            f: 1 (212) 446 8575</p>
          <br>
        </div>
        <!-- end col-4 -->
        <div class="col-md-4 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.2s">
          <h4>E-MAIL</h4>
          <a href="#">SAY HELLLO</a> </div>
        <!-- end col-4 -->
        <div class="col-xs-12 wow fadeIn" data-wow-delay="0.1s">
          <form>
            <div class="form-group">
              <label>Your name</label>
              <input type="text">
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <label>Your e-mail</label>
              <input type="text">
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <label>Subject</label>
              <input type="text">
            </div>
            <!-- end form-group -->
            <div class="form-group">
              <label>Your message</label>
              <textarea></textarea>
            </div>
            <!-- end form-group -->

            <div class="form-group">
              <button type="submit">SUBMIT</button>
            </div>
            <!-- end form-group -->
          </form>
        </div>
        <!-- end col-12 -->
      </div>
      <!-- end row -->
    </div>
    <!-- end container -->
  </section>
  <!-- end contact-us -->


{% endblock content %}

templates/menu.html
<nav class="top-menu">
	<div class="video-bg hidden-sm hidden-xs">
    	<video src="videos/video2.mp4" autoplay loop></video>
    </div>
    <!-- end video-bg -->
  <ul>
    <li><a href="abouto.html" class="transition"><span data-hover="ABOUTO">ABOUT US</span></a></li>
		<li><a href="contacto.html" class="transition"><span data-hover="CONTACTO">SERVICES</span></a></li>
		<li><a href="{% url "website:contact" %}" class="transition"><span data-hover="WORKO">CONTACT US</span></a></li>
    <li><a href="blogo.html" class="transition"><span data-hover="BLOGO">BLOG</span></a></li>    
  </ul>
</nav>